# Generated by Django 4.2.30 on 2026-09-05 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('BUSINESS', 'Business')], default='PERSONAL', max_length=10)),
                ('username_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, choices=[('NATIONWIDE', 'Nationwide'), ('ABUJA', 'FCT - Abuja'), ('LAGOS', 'Lagos'), ('KANO', 'Kano'), ('RIVERS', 'Rivers')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, choices=[('NATIONWIDE', 'Nationwide'), ('ABUJA', 'FCT - Abuja'), ('LAGOS', 'Lagos'), ('KANO', 'Kano'), ('RIVERS', 'Rivers')], max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=20, null=True)),
                ('income_bracket', models.CharField(blank=True, choices=[('UNDER_50K', 'Under ₦50,000'), ('50K_150K', '₦50,000 - ₦150,000'), ('150K_300K', '₦150,000 - ₦300,000'), ('ABOVE_300K', 'Above ₦300,000')], max_length=20, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('O_LEVEL', "O'Level (WAEC/NECO)"), ('OND_HND', 'OND/HND'), ('BACHELORS', "Bachelor's Degree"), ('POST_GRADUATE', 'Post-Graduate (Master/PhD)')], max_length=20, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('FORMAL', 'Formal Corporate'), ('INFORMAL', 'Informal/Trader'), ('STUDENT', 'Student'), ('NYSC', 'NYSC Corp Member'), ('UNEMPLOYED', 'Unemployed')], max_length=20, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('year_of_incorporation', models.PositiveIntegerField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
