# Generated by Django 4.2.30 on 2026-09-05 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('min_age', models.PositiveIntegerField(default=18)),
                ('max_age', models.PositiveIntegerField(default=100)),
                ('business_sector', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(choices=[('NATIONWIDE', 'Nationwide'), ('LAGOS', 'Lagos'), ('ABUJA', 'FCT - Abuja'), ('KANO', 'Kano'), ('RIVERS', 'Rivers')], default='NATIONWIDE', max_length=50)),
                ('income_bracket', models.CharField(choices=[('ANY', 'Any Income'), ('UNDER_50K', 'Under ₦50,000'), ('50K_150K', '₦50,000 - ₦150,000'), ('ABOVE_150K', 'Above ₦150,000')], default='ANY', max_length=20)),
                ('education_level', models.CharField(choices=[('ANY', 'Any Education Level'), ('O_LEVEL', "O'Level (WAEC/NECO)"), ('OND_HND', 'OND/HND'), ('BACHELORS', "Bachelor's Degree")], default='ANY', max_length=20)),
                ('employment_status', models.CharField(choices=[('ANY', 'Any Status'), ('FORMAL', 'Formal Corporate'), ('INFORMAL', 'Informal/Trader'), ('STUDENT', 'Student'), ('NYSC', 'NYSC Corp Member'), ('UNEMPLOYED', 'Unemployed')], default='ANY', max_length=20)),
                ('cost_per_response', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_respondents_needed', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for an unending survey', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.question')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.question')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.choice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
